fix builder indentation

diff --git a/builder/pwnagotchi.yml b/builder/pwnagotchi.yml
--- a/builder/pwnagotchi.yml
+++ b/builder/pwnagotchi.yml
@@ -115,11 +115,11 @@
           - cryptsetup
           - dnsmasq
           - python3-rpi.gpio
-          - bison       # nexmon
-          - flex        # nexmon
-          - qpdf        # nexmon
+          - bison # nexmon
+          - flex # nexmon
+          - qpdf # nexmon
           - libgmp3-dev # nexmon
-          - texinfo     # nexmon
+          - texinfo # nexmon
 
   tasks:
     - name: change hostname
@@ -189,11 +189,11 @@
         name: "{{ packages.apt.install }}"
         state: present
 
-  - name: configure dphys-swapfile
-    lineinfile:
-      path: /etc/dphys-swapfile
-      regexp: "^CONF_SWAPSIZE=.*$"
-      line: "CONF_SWAPSIZE=512"
+    - name: configure dphys-swapfile
+      lineinfile:
+        path: /etc/dphys-swapfile
+        regexp: "^CONF_SWAPSIZE=.*$"
+        line: "CONF_SWAPSIZE=512"
 
     - name: clone papirus repository
       git:
@@ -225,28 +225,28 @@
         regexp: "#EPD_SIZE=2.0"
         line: "EPD_SIZE=2.0"
 
-  - name: Delete papirus content & directory
-    file:
-      state: absent
-      path: /usr/local/src/gratis
-    when: gratisgit.changed
+    - name: Delete papirus content & directory
+      file:
+        state: absent
+        path: /usr/local/src/gratis
+      when: gratisgit.changed
 
-  # pip v20.3 uses a newer dependency resolver that better handles our unique situation.
-  # Specifically, it handles mismatches between direct requirements without extras and
-  # indirect requirements that do want extras (e.g. gym vs stable-baselines->gym[atari]).
-  - name: Upgrade pip
-    pip:
-      name: "pip"
-      version: ">=20.3"
+    # pip v20.3 uses a newer dependency resolver that better handles our unique situation.
+    # Specifically, it handles mismatches between direct requirements without extras and
+    # indirect requirements that do want extras (e.g. gym vs stable-baselines->gym[atari]).
+    - name: Upgrade pip
+      pip:
+        name: "pip"
+        version: ">=20.3"
 
-  # We need the --ignore-installed option so that pip simply overwrites/upgrades existing
-  # packages instead of trying to uninstall them first.  While this sounds dangerous,
-  # this matches the legacy behavior of pip.  This is required to prevent pip from trying
-  # (and failing) to uninstall python packages that were originally installed via apt.
-  - name: Install pwnagotchi from source archive
-    pip:
-      name: /usr/local/src/pwnagotchi/pwnagotchi-{{ pwnagotchi.version }}.tar.gz
-      extra_args: --verbose --prefer-binary --ignore-installed
+    # We need the --ignore-installed option so that pip simply overwrites/upgrades existing
+    # packages instead of trying to uninstall them first.  While this sounds dangerous,
+    # this matches the legacy behavior of pip.  This is required to prevent pip from trying
+    # (and failing) to uninstall python packages that were originally installed via apt.
+    - name: Install pwnagotchi from source archive
+      pip:
+        name: /usr/local/src/pwnagotchi/pwnagotchi-{{ pwnagotchi.version }}.tar.gz
+        extra_args: --verbose --prefer-binary --ignore-installed
 
     - name: create /usr/local/share/pwnagotchi/ folder
       file:
@@ -258,50 +258,50 @@
         repo: https://github.com/evilsocket/pwnagotchi-plugins-contrib.git
         dest: /usr/local/share/pwnagotchi/available-plugins
 
-  - name: download and install pwngrid
-    unarchive:
-      src: "{{ packages.pwngrid.url }}"
-      dest: /usr/bin
-      remote_src: yes
-      mode: 0755
+    - name: download and install pwngrid
+      unarchive:
+        src: "{{ packages.pwngrid.url }}"
+        dest: /usr/bin
+        remote_src: yes
+        mode: 0755
 
-  # Install go-1.19.4
-  - name: Install go-1.19.4
-    unarchive:
-      src: https://go.dev/dl/go1.19.4.linux-armv6l.tar.gz
-      dest: /usr/local
-      remote_src: yes
-    register: golang
+    # Install go-1.19.4
+    - name: Install go-1.19.4
+      unarchive:
+        src: https://go.dev/dl/go1.19.4.linux-armv6l.tar.gz
+        dest: /usr/local
+        remote_src: yes
+      register: golang
 
-  - name: Update .bashrc for go-1.19.4
-    blockinfile:
-      dest: /home/pi/.bashrc
-      state: present
-      block: |
-        export GOPATH=$HOME/go
-        export PATH=/usr/local/go/bin:$PATH:$GOPATH/bin
-      insertafter: EOF
-    when: golang.changed
+    - name: Update .bashrc for go-1.19.4
+      blockinfile:
+        dest: /home/pi/.bashrc
+        state: present
+        block: |
+          export GOPATH=$HOME/go
+          export PATH=/usr/local/go/bin:$PATH:$GOPATH/bin
+        insertafter: EOF
+      when: golang.changed
 
-  - name: Install bettercap v2.32
-    shell: "export GOPATH=$HOME/go && export PATH=/usr/local/go/bin:$PATH:$GOPATH/bin && go env -w GO111MODULE=off && go get github.com/bettercap/bettercap && cd $GOPATH/src/github.com/bettercap/bettercap && make build && make install"
-    args:
-      executable: /bin/bash
-    register: bettercap
+    - name: Install bettercap v2.32
+      shell: "export GOPATH=$HOME/go && export PATH=/usr/local/go/bin:$PATH:$GOPATH/bin && go env -w GO111MODULE=off && go get github.com/bettercap/bettercap && cd $GOPATH/src/github.com/bettercap/bettercap && make build && make install"
+      args:
+        executable: /bin/bash
+      register: bettercap
 
-  - name: Link bettercap v2.32
-    command: ln -s /usr/local/bin/bettercap /usr/bin/bettercap
-    when: bettercap.changed
+    - name: Link bettercap v2.32
+      command: ln -s /usr/local/bin/bettercap /usr/bin/bettercap
+      when: bettercap.changed
 
-  # - name: download and install bettercap
-  #   unarchive:
-  #     src: "{{ packages.bettercap.url }}"
-  #     dest: /usr/bin
-  #     remote_src: yes
-  #     exclude:
-  #       - README.md
-  #       - LICENSE.md
-  #     mode: 0755
+    # - name: download and install bettercap
+    #   unarchive:
+    #     src: "{{ packages.bettercap.url }}"
+    #     dest: /usr/bin
+    #     remote_src: yes
+    #     exclude:
+    #       - README.md
+    #       - LICENSE.md
+    #     mode: 0755
 
     - name: clone bettercap caplets
       git:
@@ -322,103 +322,103 @@
         remote_src: yes
         mode: 0755
 
-  # # Install nexmon to fix wireless scanning (takes 2.5G of space)
-  # - name: clone nexmon repository
-  #   git:
-  #     repo: https://github.com/seemoo-lab/nexmon.git
-  #     dest: /usr/local/src/nexmon
-  #   register: nexmongit
+    # # Install nexmon to fix wireless scanning (takes 2.5G of space)
+    # - name: clone nexmon repository
+    #   git:
+    #     repo: https://github.com/seemoo-lab/nexmon.git
+    #     dest: /usr/local/src/nexmon
+    #   register: nexmongit
 
-  # - name: configure libisl
-  #   command: chdir=/usr/local/src/nexmon/buildtools/isl-0.10/ ./configure
+    # - name: configure libisl
+    #   command: chdir=/usr/local/src/nexmon/buildtools/isl-0.10/ ./configure
 
-  # - name: make libisl
-  #   command: chdir=/usr/local/src/nexmon/buildtools/isl-0.10/ make
+    # - name: make libisl
+    #   command: chdir=/usr/local/src/nexmon/buildtools/isl-0.10/ make
 
-  # - name: install libisl
-  #   command: chdir=/usr/local/src/nexmon/buildtools/isl-0.10/ make install
+    # - name: install libisl
+    #   command: chdir=/usr/local/src/nexmon/buildtools/isl-0.10/ make install
 
-  # - name: link libisl
-  #   command: ln -s /usr/local/lib/libisl.so /usr/lib/arm-linux-gnueabihf/libisl.so.10
+    # - name: link libisl
+    #   command: ln -s /usr/local/lib/libisl.so /usr/lib/arm-linux-gnueabihf/libisl.so.10
 
-  # - name: autoreconf libmpfr
-  #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ autoreconf -f -i
+    # - name: autoreconf libmpfr
+    #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ autoreconf -f -i
 
-  # - name: configure libmpfr
-  #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ ./configure
+    # - name: configure libmpfr
+    #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ ./configure
 
-  # - name: make libmpfr
-  #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ make
+    # - name: make libmpfr
+    #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ make
 
-  # - name: install libmpfr
-  #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ make install
+    # - name: install libmpfr
+    #   command: chdir=/usr/local/src/nexmon/buildtools/mpfr-3.1.4/ make install
 
-  # - name: link libmpfr
-  #   command: ln -s /usr/local/lib/libmpfr.so /usr/lib/arm-linux-gnueabihf/libmpfr.so.4
+    # - name: link libmpfr
+    #   command: ln -s /usr/local/lib/libmpfr.so /usr/lib/arm-linux-gnueabihf/libmpfr.so.4
 
-  ### OBSOLETE CODE ###
-  # - name: make firmware
-  #   shell: "cd /usr/local/src/nexmon/ && source ./setup_env.sh && make"
-  #   args:
-  #     executable: /bin/bash
+    ### OBSOLETE CODE ###
+    # - name: make firmware
+    #   shell: "cd /usr/local/src/nexmon/ && source ./setup_env.sh && make"
+    #   args:
+    #     executable: /bin/bash
 
-  # - name: make firmware patch
-  #   command: chdir=/usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ make
-  ### OBSOLETE CODE ###
+    # - name: make firmware patch
+    #   command: chdir=/usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ make
+    ### OBSOLETE CODE ###
 
-  # - name: make firmware and firmware patch
-  #   shell: "cd /usr/local/src/nexmon/ && source ./setup_env.sh && make && cd /usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ && make"
-  #   args:
-  #     executable: /bin/bash
+    # - name: make firmware and firmware patch
+    #   shell: "cd /usr/local/src/nexmon/ && source ./setup_env.sh && make && cd /usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ && make"
+    #   args:
+    #     executable: /bin/bash
 
-  # - name: backup original firmware
-  #   command: chdir=/usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ make backup-firmware
+    # - name: backup original firmware
+    #   command: chdir=/usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ make backup-firmware
 
-  # - name: install new firmware
-  #   command: chdir=/usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ make install-firmware
+    # - name: install new firmware
+    #   command: chdir=/usr/local/src/nexmon/patches/bcm43436b0/9_88_4_65/nexmon/ make install-firmware
 
-  # To shrink the final image, remove the nexmon directory (takes 2.5G of space) post build and installation
-  # - name: Delete nexmon content & directory
-  #   file:
-  #     state: absent
-  #     path: /usr/local/src/nexmon/
+    # To shrink the final image, remove the nexmon directory (takes 2.5G of space) post build and installation
+    # - name: Delete nexmon content & directory
+    #   file:
+    #     state: absent
+    #     path: /usr/local/src/nexmon/
 
-  # Install screenrc configuration
-  - name: clone screenrc repository
-    git:
-      repo: https://github.com/aluminum-ice/screenrc.git
-      dest: /usr/local/src/screenrc
-    register: screenrcgit
+    # Install screenrc configuration
+    - name: clone screenrc repository
+      git:
+        repo: https://github.com/aluminum-ice/screenrc.git
+        dest: /usr/local/src/screenrc
+      register: screenrcgit
 
-  - name: create /home/pi/.screenrc
-    copy:
-      src: /usr/local/src/screenrc/.screenrc
-      dest: /home/pi/.screenrc
-      owner: pi
-      group: pi
-      mode: '0644'
-    when: screenrcgit.changed
+    - name: create /home/pi/.screenrc
+      copy:
+        src: /usr/local/src/screenrc/.screenrc
+        dest: /home/pi/.screenrc
+        owner: pi
+        group: pi
+        mode: "0644"
+      when: screenrcgit.changed
 
-  - name: Delete screenrc content & directory
-    file:
-      state: absent
-      path: /usr/local/src/screenrc/
-    when: screenrcgit.changed
+    - name: Delete screenrc content & directory
+      file:
+        state: absent
+        path: /usr/local/src/screenrc/
+      when: screenrcgit.changed
 
-  - name: install bettercap caplets
-    make:
-      chdir: /tmp/caplets
-      target: install
-    when: capletsgit.changed
+    - name: install bettercap caplets
+      make:
+        chdir: /tmp/caplets
+        target: install
+      when: capletsgit.changed
 
-  - name: add HDMI powersave to rc.local
-    blockinfile:
-      path: /etc/rc.local
-      insertbefore: "exit 0"
-      block: |
-        if ! /opt/vc/bin/tvservice -s | egrep 'HDMI|DVI'; then
-          /opt/vc/bin/tvservice -o
-        fi
+    - name: add HDMI powersave to rc.local
+      blockinfile:
+        path: /etc/rc.local
+        insertbefore: "exit 0"
+        block: |
+          if ! /opt/vc/bin/tvservice -s | egrep 'HDMI|DVI'; then
+            /opt/vc/bin/tvservice -o
+          fi
 
     - name: create /etc/pwnagotchi folder
       file:
@@ -507,14 +507,14 @@
           You learn more about me at https://pwnagotchi.ai/
       when: hostname.changed
 
-  # Ansible's apt module has an "autoclean" option but it only removes packages
-  # that can no longer be downloaded.  Ansible v2.13 added the "clean" option
-  # which actually purges the apt cache, but that's newer than what we can
-  # install from the RasPiOS repos.  Instead, we'll manually clean the cache.
-  - name: clean apt cache
-    command: "apt-get clean"
-    args:
-      warn: false
+    # Ansible's apt module has an "autoclean" option but it only removes packages
+    # that can no longer be downloaded.  Ansible v2.13 added the "clean" option
+    # which actually purges the apt cache, but that's newer than what we can
+    # install from the RasPiOS repos.  Instead, we'll manually clean the cache.
+    - name: clean apt cache
+      command: "apt-get clean"
+      args:
+        warn: false
 
     - name: remove dependencies that are no longer required
       apt:
